apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fintech-app
  template:
    metadata:
      labels:
        app: fintech-app
    spec:
      containers:
        - name: fintech-app
          image: fola901/fintech-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fintech-secrets
                  key: DATABASE_URL